apiVersion: v1
kind: Service
metadata:
  name: {{ include "parking-service.fullname" . }}
  labels:
    app: {{- include "parking-service.labels" . | nindent 4 }}-mongodb
spec:
  selector:
    {{- include "parking-service.labels" . | nindent 4 }}
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ports:
    - port: {{ .Values.service.port }}
