apiVersion: v1
kind: Service
metadata:
  name: {{ include "parking-service.fullname" . }}
  labels:
    {{- include "parking-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "parking-service.labels" . | nindent 4 }}
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ports:
    - port: 27017
