replicaCount: 1

image:
  repository: andrazsovinec/parking-service
  tag: v1
  pullPolicy: Always

service:
  port: 5001

mongodb:
  #uri: "mongodb://mongodb-service:27017/"
  storageSize: 5Gi
  replicaCount: 1

env:
  JWT_SECRET: "my_key"

persistentVolume:
  hostPath: /data/mongodb

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: park-searcher.com
      paths:
        - path: /
          pathType: ImplementationSpecific

podLabels:
  app: parking-service
  environment: parking-dev
  team: parking-backend
  version: v1.0.0

cronjob:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
