replicaCount: 1

image:
  repository: andrazsovinec/user-service
  tag: v1
  pullPolicy: Always

service:
  port: 5000

mongodb:
  #uri: "mongodb://mongodb-service:27017/"
  storageSize: 5Gi
  replicaCount: 1

env:
  JWT_SECRET: "my_key"

persistentVolume:
  hostPath: /data/mongodb

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

ingress:
  enabled: false
  host: "user-service.example.com"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls: true
  tlsSecret: "user-service-tls"