replicaCount: 3

image:
  repository: andrazsovinec/user-service
  tag: v1
  pullPolicy: Always

service:
  port: 5000

mongodb:
  uri: "mongodb://mongodb-service:27017/"
  storageSize: 5Gi
  replicaCount: 1

env:
  JWT_SECRET: "my_key"

persistentVolume:
  hostPath: /data/mongodb
