replicaCount: 1

image:
  repository: muciferthecat/user-service
  tag: v1
  pullPolicy: Always

service:
  port: 5000

mongodb:
  #uri: "mongodb://mongodb-service:27017/"
  storageSize: 5Gi
  replicaCount: 1

env:
  JWT_SECRET: "my_key"

persistentVolume:
  hostPath: /data/mongodb

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true
  host: "user-service.example.com" # Replace with your domain name
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Optional, for TLS
  tls: true
  tlsSecret: "user-service-tls" # Secret name for HTTPS

livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
