apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-service.fullname" . }}
  labels:
    app: {{ include "frontend-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "frontend-service.labels" . | nindent 4 }}
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}