replicaCount: 1

image:
  repository: andrazsovinec/frontend
  tag: v1
  pullPolicy: Always

service:
  port: 3000

ingress:
  enabled: true
  host: "park-searcher.com"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls: true
  tlsSecret: "frontend-service-tls"

podLabels:
  app: frontend-service
  environment: frontend-dev
  team: frontend
  version: v1.0.0

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80