openapi: 3.0.0
info:
  title: PaymentService API
  version: 1.0.0
  description: API documentation for the PaymentService application
servers:
  - url: http://localhost:5002
paths:
  /api/payment/create:
    post:
      tags:
        - Payment
      summary: Create a new payment record
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  description: Amount of the payment
                  example: 100
      responses:
        201:
          description: New payment created successfully
        500:
          description: Server error

  /api/payment/getall:
    get:
      tags:
        - Payment
      summary: Retrieve all payment records for the authenticated user
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of payment records
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    email:
                      type: string
                      example: user@example.com
                    amount:
                      type: number
                      example: 100
                    date:
                      type: string
                      format: date-time
                      example: 2023-01-01T12:00:00Z
                    isActive:
                      type: boolean
                      example: true
        404:
          description: No payments found for this email
        500:
          description: Server error

  /api/payment/getone:
    get:
      tags:
        - Payment
      summary: Retrieve a specific payment record by ID
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: Payment record ID
                  example: 64babc1234567890abcdef12
      responses:
        200:
          description: Payment record retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    example: user@example.com
                  amount:
                    type: number
                    example: 100
                  date:
                    type: string
                    format: date-time
                    example: 2023-01-01T12:00:00Z
                  isActive:
                    type: boolean
                    example: true
        404:
          description: No payment with this ID
        500:
          description: Server error

  /api/payment/deactivate:
    put:
      tags:
        - Payment
      summary: Deactivate (settle) a payment record
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: Payment record ID
                  example: 64babc1234567890abcdef12
      responses:
        200:
          description: Payment settled successfully
        404:
          description: No payment with this ID or payment already settled
        500:
          description: Server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
