apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-mongodb-pv
spec:
  capacity:
    storage: {{ .Values.mongodb.storageSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistentVolume.hostPath }}