apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-mongodb-pvc
spec:
  storageClassName: "managed-premium"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.storageSize }}
