replicaCount: 1

image:
  repository: andrazsovinec/payment-service
  tag: v1
  pullPolicy: Always

service:
  port: 5002

mongodb:
  #uri: "mongodb://mongodb-service:27017/"
  storageSize: 5Gi
  replicaCount: 1

env:
  JWT_SECRET: "my_key"

persistentVolume:
  hostPath: /data/mongodb

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true
  host: "payment-service.example.com"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls: true
  tlsSecret: "payment-service-tls"

podLabels:
  app: payment-service
  environment: payment-dev
  team: payment-backend
  version: v1.0.0
