replicaCount: 1

image:
  repository: andrazsovinec/search-service
  tag: v1
  pullPolicy: Always

service:
  port: 5003

env:
  JWT_SECRET: "J3BG8hi51msf5"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: park-searcher.com
      paths:
        - path: /
          pathType: ImplementationSpecific

podLabels:
  app: search-service
  environment: search-dev
  team: search-backend
  version: v1.0.0

livenessProbe:
  httpGet:
    path: /health
    port: 5003
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 5003
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
