replicaCount: 1

image:
  repository: muciferthecat/search-service
  tag: v1
  pullPolicy: Always

service:
  port: 5003

env:
  JWT_SECRET: "my_key"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true
  host: "search-service.example.com"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls: true
  tlsSecret: "search-service-tls"

podLabels:
  app: search-service
  environment: search-dev
  team: search-backend
  version: v1.0.0

livenessProbe:
  httpGet:
    path: /health
    port: 5003
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 5003
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
